<?xml version="1.0" encoding="UTF-8"?><schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo" xmlns:umlmodell="https://skjema.geonorge.no/SOSI/produktspesifikasjon/arealressurskart-ar50/uml-modell/1.0" elementFormDefault="qualified" targetNamespace="https://skjema.geonorge.no/SOSI/produktspesifikasjon/arealressurskart-ar50/uml-modell/1.0" version="1.0">
  <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo" schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
  <import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
  <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
  <element name="ArealressursFlate" substitutionGroup="umlmodell:Fellesegenskaper" type="umlmodell:ArealressursFlateType">
    <annotation>
      <documentation>et sammenhengende areal som er tilordnet de samme egenskapsverdiene i henhold til et Arealressursklassifikasjonssystem


-- Definition --
a continuous area which has been assigned the same attribute values in accordance with an area resource classification system</documentation>
    </annotation>
  </element>
  <complexType name="ArealressursFlateType">
    <complexContent>
      <extension base="umlmodell:FellesegenskaperType">
        <sequence>
          <element name="område" type="gml:SurfacePropertyType">
            <annotation>
              <documentation>objektets utstrekning

-- Definition --
area over which an object extends</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">Flate</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="arealtype" type="gml:CodeType">
            <annotation>
              <documentation>hovedinndeling etter kriterier for vegetasjon, naturlig drenering og kulturpåvirkning

-- Definition --
main categorization according to criteria for vegetation, natural drainage and cultural impact</documentation>
              <appinfo>
                <sc:targetCodeListURI>https://register.geonorge.no/sosi-kodelister/arealressurs/arealressursarealtype</sc:targetCodeListURI>
                <sc:taggedValue tag="SOSI_navn">ARTYPE</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="skogbonitet" type="gml:CodeType">
            <annotation>
              <documentation>inndeling etter arealets evne til å produsere trevirke

-- Definition --
categorization according to the ability of the area to produce wood</documentation>
              <appinfo>
                <sc:targetCodeListURI>https://register.geonorge.no/sosi-kodelister/arealressurs/arealressursskogbonitet</sc:targetCodeListURI>
                <sc:taggedValue tag="SOSI_navn">ARSKOGBON</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="treslag" type="gml:CodeType">
            <annotation>
              <documentation>inndeling etter fordeling av kronedekket mellom bartrær og lauvtrær

-- Definition --
categorization according to the distribution of crown cover between coniferous and deciduous trees</documentation>
              <appinfo>
                <sc:targetCodeListURI>https://register.geonorge.no/sosi-kodelister/arealressurs/arealressurstreslag</sc:targetCodeListURI>
                <sc:taggedValue tag="SOSI_navn">ARTRESLAG</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="jordbruk" type="gml:CodeType">
            <annotation>
              <documentation>Temaet ’Jordbruk’ dekker samme geografiske område som klasse 20 (Jordbruk) i temaet ’Arealtype’. Temaet er basert på AR5. Egenskapsverdiene er numeriske.</documentation>
              <appinfo>
                <sc:targetCodeListURI>https://register.geonorge.no/sosi-kodelister/arealressurs/arealressursjordbruk</sc:targetCodeListURI>
              </appinfo>
            </annotation>
          </element>
          <element name="vegetasjonsdekke" type="gml:CodeType">
            <annotation>
              <documentation>informasjon om vegetasjonsdekkets frodighet på snaumark

-- Definition --
information concerning the lushness of the vegetation cover on bare land</documentation>
              <appinfo>
                <sc:targetCodeListURI>https://register.geonorge.no/sosi-kodelister/arealressurs/arealressursvegetasjonsdekke</sc:targetCodeListURI>
                <sc:taggedValue tag="SOSI_navn">ARVEGET</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="kartstandard" type="gml:CodeType">
            <annotation>
              <documentation>informasjon om hvilket klassifikasjonssystem som er brukt

-- Definition --
information concerning which classification system has been used</documentation>
              <appinfo>
                <sc:targetCodeListURI>https://register.geonorge.no/sosi-kodelister/arealressurs/arealressurskartstandard</sc:targetCodeListURI>
                <sc:taggedValue tag="SOSI_navn">ARKARTSTD</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element maxOccurs="unbounded" name="avgrensning" type="umlmodell:ArealressursGrensePropertyType"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="ArealressursFlatePropertyType">
    <sequence minOccurs="0">
      <element ref="umlmodell:ArealressursFlate"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="ArealressursGrense" substitutionGroup="umlmodell:Fellesegenskaper" type="umlmodell:ArealressursGrenseType">
    <annotation>
      <documentation>avgrensing for en eller to arealressursflater


-- Definition --
delimitation for one or two area resource surfaces</documentation>
    </annotation>
  </element>
  <complexType name="ArealressursGrenseType">
    <complexContent>
      <extension base="umlmodell:FellesegenskaperType">
        <sequence>
          <element name="grense" type="gml:CurvePropertyType">
            <annotation>
              <documentation>forløp som følger overgang mellom ulike fenomener

-- Definition --
course follwing the transition between different real world phenomena</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">Kurve</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="ArealressursGrensePropertyType">
    <sequence minOccurs="0">
      <element ref="umlmodell:ArealressursGrense"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element abstract="true" name="Fellesegenskaper" substitutionGroup="gml:AbstractFeature" type="umlmodell:FellesegenskaperType">
    <annotation>
      <documentation>abstrakt objekt som bærer en rekke egenskaper som er fagområde-uavhengige og kan benyttes for alle objekttyper

Merknad:
Spesielt i produktspesifikasjonsarbeid vil en velge egenskaper og av grensningslinjer fra denne klassen.</documentation>
    </annotation>
  </element>
  <complexType abstract="true" name="FellesegenskaperType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element name="identifikasjon" type="umlmodell:IdentifikasjonPropertyType">
            <annotation>
              <documentation>unik identifikasjon av et objekt</documentation>
            </annotation>
          </element>
          <element name="informasjon" type="string">
            <annotation>
              <documentation>generell opplysning

Merknad:
Her legges det inn utfyllende informasjon om objektet</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">INFORMASJON</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="kopidata" type="umlmodell:KopidataPropertyType">
            <annotation>
              <documentation>angivelse av at objektet er hentet fra en kopi av originaldata
Merknad:
Kan benyttes dersom man gjør et uttak av en database som ikke inneholder originaldataene.</documentation>
            </annotation>
          </element>
          <element name="kvalitet" type="umlmodell:PosisjonskvalitetPropertyType">
            <annotation>
              <documentation>beskrivelse av kvaliteten på stedfestingen

Merknad: Denne er identisk med ..KVALITET i tidligere versjoner av SOSI.</documentation>
            </annotation>
          </element>
          <element name="oppdateringsdato" type="date">
            <annotation>
              <documentation>dato for siste endring på objektetdataene

Merknad:
Oppdateringsdato kan være forskjellig fra Datafangsdato ved at data som er registrert kan bufres en kortere eller lengre periode før disse legges inn i datasystemet (databasen).

-Definition-
Date and time at which this version of the spatial object was inserted or changed in the spatial data set.</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">OPPDATERINGSDATO</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="FellesegenskaperPropertyType">
    <sequence minOccurs="0">
      <element ref="umlmodell:Fellesegenskaper"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="Identifikasjon" substitutionGroup="gml:AbstractObject" type="umlmodell:IdentifikasjonType"/>
  <complexType name="IdentifikasjonType">
    <sequence>
      <element name="lokalId" type="string">
        <annotation>
          <documentation>lokal identifikator, tildelt av dataleverendør/dataforvalter. Den lokale identifikatoren er unik innenfor navnerommet, ingen andre objekter har samme identifikator.

NOTE: Det er data leverendørens ansvar å sørge for at denne lokale identifikatoren er unik innenfor navnerommet.</documentation>
          <appinfo>
            <sc:taggedValue tag="SOSI_navn">LOKALID</sc:taggedValue>
          </appinfo>
        </annotation>
      </element>
      <element name="navnerom" type="string">
        <annotation>
          <documentation>navnerom som unikt identifiserer datakilden til objektet, starter med to bokstavs kode jfr ISO 3166. Benytter understreking  ("_") dersom data produsenten ikke er assosiert med bare et land.

NOTE 1 : Verdien for nanverom vil eies av den dataprodusent som har ansvar for de unike identifikatorene og vil registreres i "INSPIRE external  Object Identifier Namespaces Register"

Eksempel: NO_SL_AR50_2014</documentation>
          <appinfo>
            <sc:taggedValue tag="SOSI_navn">NAVNEROM</sc:taggedValue>
          </appinfo>
        </annotation>
      </element>
    </sequence>
  </complexType>
  <complexType name="IdentifikasjonPropertyType">
    <sequence>
      <element ref="umlmodell:Identifikasjon"/>
    </sequence>
  </complexType>
  <element name="Kopidata" substitutionGroup="gml:AbstractObject" type="umlmodell:KopidataType"/>
  <complexType name="KopidataType">
    <sequence>
      <element name="områdeId" type="integer">
        <annotation>
          <documentation>identifikasjon av område som dataene dekker

Merknad: Kan angis med kommunenummer eller fylkesnummer. Disse bør spesifiseres nærmere.</documentation>
          <appinfo>
            <sc:taggedValue tag="SOSI_navn">OMRÅDEID</sc:taggedValue>
          </appinfo>
        </annotation>
      </element>
      <element name="originalDatavert" type="string">
        <annotation>
          <documentation>ansvarlig etat for forvaltning av data</documentation>
          <appinfo>
            <sc:taggedValue tag="SOSI_navn">ORIGINALDATAVERT</sc:taggedValue>
          </appinfo>
        </annotation>
      </element>
      <element name="kopidato" type="date">
        <annotation>
          <documentation>dato når objektet ble kopiert fra originaldatasettet

Merknad:
Er en del av egenskapen Kopidata. Brukes i de tilfeller hvor en kopidatabase brukes til distribusjon.
Å kopiere et datasett til en kopidatabase skal ikke føre til at Oppdateringsdato blir endret.
Eventuell redigering av data i et kopidatasett medfører ny Oppdateringsdato, Datafangstdato og/eller Verifiseringsdato.</documentation>
          <appinfo>
            <sc:taggedValue tag="SOSI_navn">KOPIDATO</sc:taggedValue>
          </appinfo>
        </annotation>
      </element>
    </sequence>
  </complexType>
  <complexType name="KopidataPropertyType">
    <sequence>
      <element ref="umlmodell:Kopidata"/>
    </sequence>
  </complexType>
  <element name="Posisjonskvalitet" substitutionGroup="gml:AbstractObject" type="umlmodell:PosisjonskvalitetType"/>
  <complexType name="PosisjonskvalitetType">
    <sequence>
      <element name="målemetode" type="gml:CodeType">
        <annotation>
          <documentation>metode for måling i grunnriss (x,y), og høyde (z) når metoden er den samme som ved måling i grunnriss</documentation>
          <appinfo>
            <sc:targetCodeListURI>https://register.geonorge.no/sosi-kodelister/generelle-konsepter/4.5/m%C3%A5lemetodekode</sc:targetCodeListURI>
          </appinfo>
        </annotation>
      </element>
    </sequence>
  </complexType>
  <complexType name="PosisjonskvalitetPropertyType">
    <sequence>
      <element ref="umlmodell:Posisjonskvalitet"/>
    </sequence>
  </complexType>
</schema>
